FROM docker.io/oven/bun:1.3.14-alpine AS build
WORKDIR /app

COPY package.json ./
COPY bun.lock ./
RUN bun install

COPY . /app
RUN bun run build

# production environment
FROM docker.io/nginx:1.31.0-alpine-slim
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]